### ISSUE TITLE
presentLetter is a boolean

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/HangmanPoject#1]
https://github.com/Selemabala/HangmanPoject/blob/df5d7976a787380ddb01556cbbd59b30c420b667/HangmanPoject/Program.cs#L50-L54

present letter is a boolean variable. There's no need to check if a boolean is true/false in an if case

if(presentLetter) is equal to if(presentLetter==true) but avoid the second.

**Comment by Selemabala** [comment]
Thanks
