### ISSUE TITLE
i<LIMIT is always true inside your loop

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/HangmanPoject#2]
https://github.com/Selemabala/HangmanPoject/blob/df5d7976a787380ddb01556cbbd59b30c420b667/HangmanPoject/Program.cs#L50-L54

Your for loop doesn't allow for i to be more that LIMIT so you don't need to check that in your if case

**Comment by Selemabala** [comment]
Makes sense, I understand. Thanks
