### ISSUE TITLE
Input should be validated

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/HangmanPoject#4]
https://github.com/Selemabala/HangmanPoject/blob/3861d921cb7267e1bc86c062a00e74157834a71f/HangmanPoject/Program.cs#L38

Right now the user is able to pass null as a param, and numbers which should not be valid for your program. 

We suggest to change the approach of reading input,scrap the ReadLine() method and use ReadKey, so that the input can be validated easier
https://learn.microsoft.com/en-us/dotnet/api/system.console.readkey?view=net-8.0

**Comment by Selemabala** [comment]
https://github.com/Selemabala/HangmanPoject/commit/3861d921cb7267e1bc86c062a00e74157834a71f

3861d92
Resolved the line  38  userInputletter = Console.ReadLine()[0];  to  userInputletter = Console.ReadKey().KeyChar;.This way the user is not  able to pass null as a param, and numbers which should not be valid for the program. This enables the
input to be validated easier

Also line 70-73 were omitted this it was unnecessary if statement
 if (i < LIMIT)
            {
                Console.WriteLine("Try again");
            }

**Comment by Selemabala** [comment]
1: Input Validation has been put

2: Resolved the line 38 userInputletter = Console.ReadLine()[0]; to userInputletter = Console.ReadKey().KeyChar;.This way the user is not able to pass null as a param, and numbers which should not be valid for the program. This enables the
input to be validated easier

3: Line 70-73 were omitted this it was unnecessary if statement
if (i < LIMIT)
{
Console.WriteLine("Try again");
}
